### ISSUE TITLE
How to not display box when no birthdays

### ISSUE THREAD

**Issue by kevinoost** [NicolasSiver/nodebb-widget-ns-birthdays#5]
Hi,

When there is no birthday of someone, we still see the box that comes with the panel-body and panel-default div elements.
Any idea how we could fix this issue?

I have tried the :empty css3 trick, but that does not seem to work.

Thanks!

**Comment by NicolasSiver** [comment]
Hello,

In my personal theme, I'm not using panels. The plugin is capable to hide completely if there are no birthdays, but _panel_ is not that smart.

**Comment by kevinoost** [comment]
Hi Nicolas, thanks for your response. Yeah, I guess it is better to remove it
